### PR TITLE
feat(discovery): add search suggestion api

### PR DESCRIPTION
**Pull request by StewartJingga**
## Discovery
Expose new endpoint `/v1/search/suggest` with below response

### Request
```
[GET] /v1/search/suggest?text="tes"
```

### Response
```
{
  "suggestions": ["test", "tesla"]
}
```

### CODE REVIEW

**Review by mabdh — APPROVED** [review]

**Comment by mabdh** [comment]
All look good. LGTM.

**Comment by StewartJingga** [comment]
@mabdh changing to completion suggester 🙏 
https://github.com/odpf/columbus/pull/40/commits/e9d683b377176bdafbfeb50789cc5a66faac9b85

**Comment by mabdh** [comment]
> @mabdh changing to completion suggester 🙏 [e9d683b](https://github.com/odpf/columbus/commit/e9d683b377176bdafbfeb50789cc5a66faac9b85)

I am testing this in integration now.

**Comment by mabdh** [comment]
Looks good. LGTM

**Pull request merged**
